### ISSUE TITLE
mypyc benchmark doesn't seem to run mypyc

### ISSUE THREAD

**Issue by mdboom** [pyston/python-macrobenchmarks#5]
I'm working on updating the mypy benchmark to be compatible with Python 3.11 (primarily by just updating the dependencies).  However, I've run into a small snag.  The `mypyc` benchmark, which is a "subbenchmark" of `mypy`, doesn't actually seem to run `mypyc` -- it just runs the same thing as the `mypy` benchmark with 50 loops rather than 20.  Additionally, there is a bug when running in the `pyperformance` harness since the results of both of these use the same name (`mypy`).

I think we should either:

1) Add a new benchmark that legitimately runs `mypyc`
2) Just remove the `mypyc` benchmark

Thoughts?

**Comment by kmod** [comment]
Ah thanks for pointing this out, looks like this needs a little bit more work so I just removed the mypyc benchmark for now.

Just a word of caution that the mypy wheels on pypi are built using mypyc whereas their sdist is configured to not use mypyc, so this means that if you're comparing a Python version that has a mypy wheel vs one that doesn't you will see a large performance difference due to this. I think this should be addressed by https://github.com/python/pyperformance/pull/195 in newer versions of pyperformance
